version: 0.0
os: linux

files:
  - source: index.html
    destination: /var/www/html

  - source: hello
    destination: /var/www/html

  - source: health.html
    destination: /var/www/html

file_exists_behavior: OVERWRITE

hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 180
      runas: root